import localFont from "next/font/local";
import "./globals.css";

const circular = localFont({
  src: "./fonts/circularweb-book.woff2",
  variable: "--font-circular",
});

const zentry = localFont({
  src: "./fonts/zentry-regular.woff2",
  variable: "--font-zentry",
});

const general = localFont({
  src: "./fonts/general.woff2",
  variable: "--font-general",
});

const robertMedium = localFont({
  src: "./fonts/robert-medium.woff2",
  variable: "--font-robert-medium",
});

const robertRegular = localFont({
  src: "./fonts/robert-regular.woff2",
  variable: "--font-robert-regular",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`w-full ${circular.variable} ${zentry.variable} ${general.variable} ${robertMedium.variable} ${robertRegular.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
